[theme]

# Primary accent for interactive elements
primaryColor = '#82246f'

# Background color for the main content area
backgroundColor = '#28182e'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#5f8dc2'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"